# product-service.yml

server:
  port: 8200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PRODUCT_DB_URL:jdbc:mysql://localhost:3306/e_commerce_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:change_me}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

  web:
    error:
      include-message: always
      include-binding-errors: always

logging:
  level:
    root: INFO
    com.smartmart.productservice: DEBUG

  file:
    name: logs/product-service.log